import { StyleSheet } from "react-native"

export const styles = StyleSheet.create({
    topPag: {
        width: "100%",
        height: 100,
        alignItems: "center",
    },
    topPagContent: {
        borderColor: "black",
        // borderWidth: 1,
        // borderLeftWidth: 6,
        // borderRightWidth: 6,
        // borderBottomWidth: 6,
        borderBottomLeftRadius: 15,
        borderBottomRightRadius: 15,
        paddingTop: 1,
        paddingBottom: 16,
        paddingHorizontal: 35,
    },
    topPagContentText: {
        width: 230,
        height: 65,
    },
    gifMudanca: {
        width: 335,
        height: 335,
        resizeMode: "contain",
    },
    gif: {
    width: 250,
    height: 250,
    resizeMode: "contain",
    },
    topPagBarsFoodAndWater: {
        marginTop: 10,
        alignItems: "center",
        justifyContent: "space-around",
        flexDirection: "row",
        height: 30,
    },
    topPagBarsFood: {
        flexDirection: "row",
        backgroundColor: "white",
        width: 150,
        borderRadius: 20,
        justifyContent: "space-between",
        height: "100%",
    },
    topPagBarsFoodBlockOne: {
        borderRightWidth: 1,
        borderTopLeftRadius: 110,
        borderBottomLeftRadius: 110,
        height: "100%",
        backgroundColor: "orange",
        width: "25%",
    },
    topPagBarsFoodBlockTwo: {
        borderLeftWidth: 1,
        height: "100%",
        backgroundColor: "orange",
        width: "25%",
    },
    topPagBarsFoodBlockThree: {
        borderLeftWidth: 1,
        height: "100%",
        backgroundColor: "orange",
        width: "25%",
    },
    topPagBarsFoodBlockFour: {
        borderLeftWidth: 2,
        borderTopRightRadius: 110,
        borderBottomRightRadius: 110,
        height: "100%",
        backgroundColor: "orange",
        width: "25%",
    },
    topPagBarsWater: {
        flexDirection: "row",
        backgroundColor: "white",
        width: 150,
        borderRadius: 20,
        justifyContent: "space-between",
        height: "100%",
    },
    topPagBarsWaterBlockOne: {
        borderRightWidth: 1,
        borderTopLeftRadius: 110,
        borderBottomLeftRadius: 110,
        height: "100%",
        backgroundColor: "#1CD4E9",
        width: "25%",
    },
    topPagBarsWaterBlockTwo: {
        borderLeftWidth: 1,
        height: "100%",
        backgroundColor: "#1CD4E9",
        width: "25%",
    },
    topPagBarsWaterBlockThree: {
        borderLeftWidth: 1,
        height: "100%",
        backgroundColor: "#1CD4E9",
        width: "25%",
    },
    topPagBarsWaterBlockFour: {
        borderLeftWidth: 2,
        borderTopRightRadius: 110,
        borderBottomRightRadius: 110,
        height: "100%",
        backgroundColor: "#1CD4E9",
        width: "25%",
    },
})
